apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: ashuk8s1
spec: {}
status: {}
---
apiVersion: v1
kind: Pod
metadata:
  namespace: ashuk8s1 # injecting namespace info 
  creationTimestamp: null
  labels:
    run: ashupod2
  name: ashupod2
spec:
  containers:
  - image: ubuntu
    name: ashupod2
    command: ["sh","-c","sleep 600000"]
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  namespace: ashuk8s1 # namespace info 
  creationTimestamp: null
  labels:
    app: ashutoshhsvc1
  name: ashutoshhsvc1
spec:
  ports:
  - name: 1234-80
    port: 1234
    protocol: TCP
    targetPort: 80
    nodePort: 32766 # choosing static port 
  selector:
    app: ashutoshhsvc1
  type: NodePort
status:
  loadBalancer: {}